// Auth module barrel export
export { authApi } from './api'
export { useCurrentUser, useUsers, useLogin, useLogout, useUpdateUserPermissions, usePermissions, resolvePermissions } from './hooks'
export type { UsePermissionsReturn } from './hooks'
export { PermissionGate, ProtectedRoute } from './components'
export type { PermissionGateProps, ProtectedRouteProps } from './components'
export { AuthProvider, useAuthContext } from './context/AuthContext'
export { LoginPage, AuthCallbackPage } from './pages'
export type { User } from './types'
export { hasRole, isAdmin, isGroomer, isOwner } from './utils'
